export const SET_RANDOM_NUMBERS = 'SET_RANDOM_NUMBERS'
export const UPDATE_ANSWER = 'UPDATE_ANSWER'
export const SET_START = 'SET_START'
export const SET_GAME_CONFIGURATION = 'SET_GAME_CONFIGURATION'
